### ISSUE TITLE
Pass resolved object from `sideEffect` to `prepared` component instance as props.

### ISSUE THREAD

**Issue by danscan** [fusionjs/fusion-react#147]
### Type of issue

Feature request

### Description

It would be nice to be able to use the `sideEffect` passed to `prepared` to asynchronously fetch data for a component.

I envision something like:
```javascript
// Fetch username by user id
const hoc = prepared(async (props) => {
  const userResponse = await fetch(`/users/${props.userId}.json`);
  const { username } = userResponse.json();

  return { username };
})();

const Username = ({ username }) => <h1>{username}</h1>;

export default hoc(Username);
```

### Current behavior

The value of a resolved promise returned by `sideEffect` goes nowhere.

### Expected behavior

If `sideEffect` returns a promise that resolves to an object, it extends its component instance's props, e.g: `const instanceProps = { ...sideEffectObject, ...elementProps }`. 

### Steps to reproduce

1. Create a hoc using `prepared`.
2. Return a promise that resolves an object value, e.g: `prepared(() => Promise.resolve({ test: true }))`
3. Observe that the returned object's properties are not passed to the enhanced component.

### Your environment

* fusion-react version: v1.1.0

* Node.js version (`node --version`): v8.11.2

* npm version (`npm --version`): 5.6.0

* Operating System: MacOS 10.13.6

**Comment by mlmorg** [comment]
Prepared was a stop-gap for async server-side rendering before react supports React suspense on the server. We don't want to add any more features now so that we don't make migration to that more difficult.
