### ISSUE TITLE
Can i deploy fusionjs app as static js file?

### ISSUE THREAD

**Issue by hoang17** [fusionjs/fusion-react#156]
So i would like to deploy fusionjs app on Amazon S3 or Netlify. Is it possible and how? Thanks!

**Comment by KevinGrandon** [comment]
Unfortunately this isn't supported yet since SSR and server side code is such a big part of Fusion.js. I've filed an issue in fusion-cli where this may be implemented, let's track this here: https://github.com/fusionjs/fusion-cli/issues/484
