### ISSUE TITLE
`componentWillUnmount` called without calling `componentDidMount`

### ISSUE THREAD

**Issue by supersonicclay** [fusionjs/fusion-react#158]
### Type of issue
Bug

### Current behavior

`componentWillUnmount` is called but `componentDidMount` is not

### Expected behavior

`componentWillUnmount` should only be called if `componentDidMount` is called on a component.

### Steps to reproduce

Create a component that defines `componentWillUnmount` and `componentDidMount`.

### Your environment

* fusion-react version: 1.2.1 (it worked properly in 1.1.0)

**Comment by supersonicclay** [comment]
And disabling SSR via https://github.com/fusionjs/fusion-react/issues/95#issuecomment-399980523 did not fix the issue

**Comment by KevinGrandon** [comment]
This should no longer be an issue due to https://github.com/fusionjs/fusion-react/pull/160 landing.  We should no longer be calling `componentWillUnmount`, please re-open or file a new issue with additional context if you're still seeing this.
