### ISSUE TITLE
React hooks don't work

### ISSUE THREAD

**Issue by slonoed** [fusionjs/fusion-react#225]
### Type of issue

Bug

### Description

I want to use React hooks, when a feature is released (next week).

### Current behavior

When using hooks, dev server shows error.
```
Invariant Violation: Hooks can only be called inside the body of a function component.
```

### Expected behavior

Works normally

### Steps to reproduce

1. Create new fusion app `yarn create fusion-app my-fusion-app`
2. Replace `react` and `react-dom` versions to `v16.8.0-alpha.1`
3. Run `yarn` to install new versions
4. Change `src/pages/home.js` by adding a simple hook into component function `const [a,b] = useState(0)` + add import `import React, {useState} from 'react'`

### Your environment

* fusion-react version: 1.3.4

* Node.js version (`node --version`): v8.12.0

* npm version (`npm --version`): 6.4.1

* Operating System: MacOS mojave

**Comment by slonoed** [comment]
My guess it is connected to hot reloading mechanism. 
Storybook had [similar problem](https://github.com/storybooks/storybook/issues/4691)

**Comment by conradreuter** [comment]
A quick fix might be the following:

```
// @flow
import {prepared} from 'fusion-react';
import {noop} from 'lodash';
import React, {type ComponentType} from 'react';

function makeHooksWork<TProps: {}>(
  Component: ComponentType<TProps>
): ComponentType<TProps> {
  return prepared(noop, {defer: true})(Component);
}

const MakeHooksWork = makeHooksWork(React.Fragment);

export {makeHooksWork, MakeHooksWork};
```

Wrap your root element in `<MakeHooksWork>...</MakeHooksWork>` and then hooks will work.

This will break components that rely on the `prepare` mechanism.

**Comment by conradreuter** [comment]
I just found out about `exclude`, which should also do the trick.

**Comment by chrisirhc** [comment]
When using `split`, hooks will not work.
Perhaps we should keep this open until it's resolved?
