### ISSUE TITLE
Provide React.Context for usage with Hooks.

### ISSUE THREAD

**Issue by VladimirMilenko** [fusionjs/fusion-react#239]
### Type of issue
Feature request

### Description
Use React.createContext for client context provider.

### Current behavior

Currently, context is Provided via `getChildContext`. But there is a workaround, you can use ProviderPlugin to use custom provider which can solve the issue.

### Expected behavior

Use React 16.3 context, and expose this context from package.
So, that you can use `useContext` to create hooks for accessing plugin-provided values to allow usage without HOCs.

**Comment by slonoed** [comment]
What is the status of this issue?

**Comment by mlmorg** [comment]
We're planning to support old+new context in the next 1-2 sprint (2-4 weeks) across all of our plugins.

**Comment by micburks** [comment]
#242 adds [`useService`](https://github.com/fusionjs/fusion-react#useservice), which is similar to what you're suggesting. This will work with simple plugins, however some of our plugins have a more involved usage. We are planning to refactor these plugins within the next 1-2 weeks to make hooks first class in fusion-react.
