### ISSUE TITLE
Unable to disable server side rendering (react component using window fails)

### ISSUE THREAD

**Issue by chrisgervang** [fusionjs/fusion-react#95]
### Type of issue

bug

### Description

The example in the readme to disable SSR doesn't seem to actually disable it since window is still trying to be called from the server side.

### Current behavior

```
2018-02-21T02:56:17.763Z - fatal: window is not defined stack=ReferenceError: window is not defined
    at Project._onResize (/Users/chr/code/tools-monorepo/jetson/src/components/project.js:58:1)
    at Project.componentWillMount (/Users/chr/code/tools-monorepo/jetson/src/components/project.js:49:1)
    at renderCompositeElementInstance (/Users/chr/code/tools-monorepo/node_modules/fusion-react-async/src/prepare.js:19:14)
    at prepareCompositeElement.then.prepareConfig (/Users/chr/code/tools-monorepo/node_modules/fusion-react-async/src/prepare.js:56:12)
    at <anonymous>
```
<img width="829" alt="screen shot 2018-02-20 at 7 00 21 pm" src="https://user-images.githubusercontent.com/2461547/36461034-55ff6714-1670-11e8-86bf-8ecda21ed64f.png">

### Expected behavior

Function should run in client side

### Steps to reproduce

1. Follow the disable server side rendering example
2. Implement a basic window function, like an event listener
3. Run function at runtime

### Your environment

* fusion-react version: 1.0.2

* Node.js version (`node --version`): 8.9.4

* npm version (`npm --version`): 5.6.0

* Operating System: MacOS

**Comment by KevinGrandon** [comment]
Sorry about the bug. For certain routes you can enhance the `SSRDeciderToken`, but I don't believe that this will render your react tree. For the reported issue, you could potentially add your resize handler inside of `componentDidMount` instead of `componentWillMount`.

I'm unfortunately not aware of another way to disable SSR, we'll look into the bug and try to get the docs to be accurate.

**Comment by ganemone** [comment]
You can disable server side rendering by registering a custom render function on the `RenderToken` imported from `fusion-core`. For example:

```js
import {RenderToken} from 'fusion-core';
...
__NODE__ && app.register(RenderToken, () => "<div id='root'></div>");
```
